---
- name: Basics for Debian derivatives
  hosts: all
  become: yes

  tasks:

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Update all packages to the latest version
      ansible.builtin.apt:
        upgrade: yes

    - name: Install favorite packages
      ansible.builtin.apt:
        state: latest
        pkg: 
        - vim
        - vim-gtk3
        - curl
        - tmux
        - git
        - python3
        - python3-pip
        - python3-venv
        - sqlite3
        - sqlite3-doc
        - ufw
#        - xclip
#        - xscreensaver

    - name: Install vscode on Raspberry Pi devices
      ansible.builtin.apt:
        state: latest
        pkg: 
        - code
      when: inventory_hostname in groups['rpi']
 
    - name: Display all variables/facts known for a host
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]
        verbosity: 2

    - name: Output distribution
      ansible.builtin.debug:
        msg: Distribution {{ ansible_distribution }}

