---
- name: Basics for Debian derivatives
  hosts: all
  become: yes

  tasks:

    - name: Enable ufw
      community.general.ufw:
        state: enabled

    # Using some port other than the default may add a bit more security
    # but don't count on obscurity for much
    - name: Allow SSH through ufw
      community.general.ufw:
        rule: allow
        port: ssh
